{% set name = "recycle" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/steinwurf/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: dcda732e4be5986b0947e2b9b0168f9b3bf675bc9305663afb3254b872191dd8
    patches:
      - patches/add_cmake_pkg_config.patch

  - path: patches/cmake
    folder: cmake

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

test:
  commands:
    - test -e ${PREFIX}/include/recycle/no_locking_policy.hpp  # [unix]
    - test -e ${PREFIX}/include/recycle/shared_pool.hpp  # [unix]
    - test -e ${PREFIX}/include/recycle/unique_pool.hpp  # [unix]
    - test -e ${PREFIX}/lib/cmake/recycle/recycle-targets.cmake  # [unix]
    - test -e ${PREFIX}/lib/cmake/recycle/recycle-config.cmake  # [unix]
    - test -e ${PREFIX}/lib/cmake/recycle/recycle-config-version.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\recycle\no_locking_policy.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\recycle\shared_pool.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\recycle\unique_pool.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\recycle\recycle-targets.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\recycle\recycle-config.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\recycle\recycle-config-version.cmake (exit 1)  # [win]

about:
  home: https://github.com/steinwurf/recycle
  summary: A simple C++ resource pool implementation
  description: recycle is an implementation of a simple C++ resource pool.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - DerThorsten
